#!/bin/bash

# Setup script for timjmitchell.com local development
# This script initializes the local environment with one command

set -e

echo "🚀 Setting up timjmitchell.com development environment..."

# Check prerequisites
echo "📋 Checking prerequisites..."

if ! command -v node &> /dev/null; then
 echo "❌ Node.js is not installed. Please install Node.js 18+ first."
 exit 1
fi

if ! command -v docker &> /dev/null; then
 echo "❌ Docker is not installed. Please install Docker first."
 exit 1
fi

if ! docker info &> /dev/null; then
 echo "❌ Docker is not running. Please start Docker first."
 exit 1
fi

echo "✅ Prerequisites met"

# Install npm dependencies
echo "📦 Installing npm dependencies..."
npm install

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
 echo "📦 Installing Supabase CLI..."
 npm install -g supabase
fi

# Start Supabase local instance
echo "🗄️ Starting Supabase local instance..."
supabase start

# Get Supabase credentials
echo "🔑 Retrieving Supabase credentials..."
SUPABASE_URL=$(supabase status --output json | grep -o '"API URL": "[^"]*' | grep -o '[^"]*$')
SUPABASE_ANON_KEY=$(supabase status --output json | grep -o '"anon key": "[^"]*' | grep -o '[^"]*$')
SUPABASE_SERVICE_ROLE_KEY=$(supabase status --output json | grep -o '"service_role key": "[^"]*' | grep -o '[^"]*$')

# Create .env.local file
echo "📝 Creating .env.local file..."
cat > .env.local << EOF
# Supabase Configuration (Local Development)
# Generated by setup.sh - DO NOT COMMIT

NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
EOF

echo "✅ .env.local created"

# Run database migrations
echo "🔄 Running database migrations..."
supabase db reset

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo " 1. Run 'npm run dev' to start the development server"
echo " 2. Visit http://localhost:3000 to view the site"
echo " 3. Visit http://127.0.0.1:54323 to access Supabase Studio"
echo ""
